export const PARTNER_IMAGE_RECOMMENDED_WIDTH = 1200;
export const PARTNER_IMAGE_RECOMMENDED_HEIGHT = 900;

export const PARTNER_IMAGE_DISPLAY_ASPECT_CLASS = "aspect-[4/3]";
export const PARTNER_IMAGE_COMPACT_ASPECT_CLASS = "aspect-square";
export const PARTNER_IMAGE_PLACEHOLDER_ASPECT_CLASS = PARTNER_IMAGE_DISPLAY_ASPECT_CLASS;

export function getPartnerImageRecommendedLabel() {
  return `${PARTNER_IMAGE_RECOMMENDED_WIDTH}×${PARTNER_IMAGE_RECOMMENDED_HEIGHT}px`;
}
