-- Board reports + comment IP (run in Supabase SQL Editor)

alter table public.board_comments
  add column if not exists user_ip inet;

create index if not exists board_comments_user_ip_idx
  on public.board_comments (user_ip);

create table if not exists public.board_reports (
  id bigint generated by default as identity primary key,
  post_id uuid references public.board_posts(id) on delete cascade,
  comment_id uuid references public.board_comments(id) on delete cascade,
  reason text not null,
  reporter_ip inet,
  is_reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint board_reports_target_check check (
    (post_id is not null and comment_id is null)
    or (comment_id is not null)
  )
);

create unique index if not exists board_reports_unique_post_reporter
  on public.board_reports (post_id, reporter_ip)
  where comment_id is null and reporter_ip is not null;

create unique index if not exists board_reports_unique_comment_reporter
  on public.board_reports (comment_id, reporter_ip)
  where comment_id is not null and reporter_ip is not null;

create index if not exists board_reports_pending_idx
  on public.board_reports (is_reviewed, created_at desc);

alter table public.board_reports enable row level security;

drop policy if exists "board_reports_admin_all" on public.board_reports;
create policy "board_reports_admin_all"
  on public.board_reports for all to authenticated
  using (true) with check (true);

drop function if exists public.create_user_board_comment(uuid, text, text, text);
drop function if exists public.create_user_board_comment(uuid, text, text, text, uuid);
drop function if exists public.create_user_board_comment(uuid, text, text, text, uuid, boolean);
drop function if exists public.create_user_board_comment(uuid, text, text, text, uuid, boolean, inet);

create or replace function public.create_user_board_comment(
  p_post_id uuid,
  p_author_name text,
  p_content text,
  p_password text,
  p_parent_id uuid default null,
  p_is_secret boolean default false,
  p_user_ip inet default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  post_hidden boolean;
  parent_post_id uuid;
  parent_hidden boolean;
  store_admin_password boolean;
  secret_enabled boolean;
  ip_enabled boolean;
begin
  select is_hidden into post_hidden from board_posts where id = p_post_id;

  if post_hidden is null or post_hidden then
    raise exception 'Post not found';
  end if;

  if p_parent_id is not null then
    select post_id, is_hidden
    into parent_post_id, parent_hidden
    from board_comments
    where id = p_parent_id;

    if parent_post_id is null or parent_hidden then
      raise exception 'Parent comment not found';
    end if;

    if parent_post_id <> p_post_id then
      raise exception 'Parent comment not found';
    end if;
  end if;

  if char_length(trim(p_author_name)) = 0 or char_length(trim(p_content)) = 0 then
    raise exception 'Author and content are required';
  end if;

  if char_length(trim(p_password)) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  secret_enabled := public.is_board_secret_comments_enabled();
  if coalesce(p_is_secret, false) and not secret_enabled then
    raise exception 'Secret comments are disabled';
  end if;

  ip_enabled := public.is_board_ip_moderation_enabled();
  store_admin_password := public.is_admin_user_password_visible();

  insert into board_comments (
    post_id,
    parent_id,
    author_name,
    content,
    password_hash,
    admin_visible_password,
    is_secret,
    user_ip
  )
  values (
    p_post_id,
    p_parent_id,
    trim(p_author_name),
    trim(p_content),
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    case when store_admin_password then p_password else null end,
    case when secret_enabled then coalesce(p_is_secret, false) else false end,
    case when ip_enabled then p_user_ip else null end
  )
  returning id into new_id;

  return new_id;
end;
$$;

grant execute on function public.create_user_board_comment(uuid, text, text, text, uuid, boolean, inet) to anon, authenticated;

notify pgrst, 'reload schema';
