-- Non-member board IP moderation (status 1~4 + banned_ips)
-- Run in Supabase SQL Editor after board-secret-posts.sql

alter table public.site_settings
  add column if not exists board_ip_moderation_enabled boolean not null default false;

alter table public.board_posts
  add column if not exists user_ip inet;

alter table public.board_posts
  add column if not exists status integer not null default 1;

alter table public.board_posts
  drop constraint if exists board_posts_status_check;

alter table public.board_posts
  add constraint board_posts_status_check check (status between 1 and 4);

create table if not exists public.banned_ips (
  id bigint generated by default as identity primary key,
  ip_address inet not null unique,
  reason text,
  created_at timestamp with time zone not null default now()
);

alter table public.banned_ips enable row level security;

drop policy if exists "banned_ips_admin_all" on public.banned_ips;
create policy "banned_ips_admin_all"
  on public.banned_ips for all to authenticated
  using (true) with check (true);

create index if not exists board_posts_user_ip_idx on public.board_posts (user_ip);
create index if not exists banned_ips_ip_address_idx on public.banned_ips (ip_address);

create or replace function public.is_board_ip_moderation_enabled()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select board_ip_moderation_enabled from public.site_settings where id = 1 limit 1),
    false
  );
$$;

create or replace function public.is_ip_banned(p_ip inet)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.banned_ips b
    where b.ip_address = p_ip
  );
$$;

create or replace function public.resolve_board_post_status_for_ip(p_ip inet)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select greatest(
    1,
    least(
      coalesce(
        (
          select max(p.status)
          from public.board_posts p
          where p.user_ip = p_ip
            and p.password_hash is not null
        ),
        1
      ),
      4
    )
  );
$$;

drop function if exists public.create_user_board_post(text, text, text, text, text);
drop function if exists public.create_user_board_post(text, text, text, text, text, boolean);
drop function if exists public.create_user_board_post(text, text, text, text, text, boolean, inet);

create or replace function public.create_user_board_post(
  p_board_type text,
  p_title text,
  p_author_name text,
  p_content text,
  p_password text,
  p_is_secret boolean default false,
  p_user_ip inet default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  store_admin_password boolean;
  secret_enabled boolean;
  ip_enabled boolean;
  next_status integer;
  hide_post boolean;
begin
  if not public.is_user_writable_board(p_board_type) then
    raise exception 'Invalid board type';
  end if;

  if char_length(trim(p_password)) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  secret_enabled := public.is_board_secret_posts_enabled();
  if coalesce(p_is_secret, false) and not secret_enabled then
    raise exception 'Secret posts are disabled';
  end if;

  ip_enabled := public.is_board_ip_moderation_enabled();

  if ip_enabled then
    if p_user_ip is null then
      raise exception 'Client IP is required';
    end if;

    if public.is_ip_banned(p_user_ip) then
      raise exception 'IP banned';
    end if;

    next_status := public.resolve_board_post_status_for_ip(p_user_ip);
  else
    next_status := 1;
  end if;

  hide_post := next_status >= 3;

  store_admin_password := public.is_admin_user_password_visible();

  insert into board_posts (
    board_type,
    title,
    author_name,
    content,
    password_hash,
    admin_visible_password,
    is_secret,
    user_ip,
    status,
    is_hidden
  )
  values (
    p_board_type,
    trim(p_title),
    trim(p_author_name),
    p_content,
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    case when store_admin_password then p_password else null end,
    case when secret_enabled then coalesce(p_is_secret, false) else false end,
    case when ip_enabled then p_user_ip else null end,
    next_status,
    hide_post
  )
  returning id into new_id;

  return new_id;
end;
$$;

drop function if exists public.list_board_posts_for_display(text, boolean, text[]);

create or replace function public.list_board_posts_for_display(
  p_board_type text default null,
  p_pinned_only boolean default false,
  p_board_types text[] default null
)
returns table (
  id uuid,
  board_type text,
  title text,
  author_name text,
  is_hidden boolean,
  is_secret boolean,
  is_pinned boolean,
  pinned_at timestamptz,
  like_count integer,
  dislike_count integer,
  view_count integer,
  status integer,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.board_type,
    p.title,
    p.author_name,
    p.is_hidden,
    coalesce(p.is_secret, false) as is_secret,
    coalesce(p.is_pinned, false) as is_pinned,
    p.pinned_at,
    coalesce(p.like_count, 0) as like_count,
    coalesce(p.dislike_count, 0) as dislike_count,
    coalesce(p.view_count, 0) as view_count,
    coalesce(p.status, 1) as status,
    p.created_at
  from public.board_posts p
  where
    case
      when p_pinned_only then
        coalesce(p.is_pinned, false) = true
        and (p_board_types is null or p.board_type = any(p_board_types))
      else
        p.board_type = p_board_type
    end
  order by
    case when p_pinned_only then p.pinned_at end desc nulls last,
    p.created_at desc;
$$;

revoke all on function public.list_board_posts_for_display(text, boolean, text[]) from public;
grant execute on function public.list_board_posts_for_display(text, boolean, text[]) to anon, authenticated;

grant execute on function public.create_user_board_post(text, text, text, text, text, boolean, inet) to anon, authenticated;
grant execute on function public.is_board_ip_moderation_enabled() to anon, authenticated;

notify pgrst, 'reload schema';
