-- Device (browser voter_key) ban — parallel to banned_ips / IP management
-- Run in Supabase SQL Editor after board-ip-moderation.sql and partner-reviews.sql

create table if not exists public.banned_voter_keys (
  id bigint generated by default as identity primary key,
  voter_key text not null unique,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.banned_voter_keys enable row level security;

drop policy if exists "banned_voter_keys_admin_all" on public.banned_voter_keys;
create policy "banned_voter_keys_admin_all"
  on public.banned_voter_keys for all to authenticated
  using (true) with check (true);

create index if not exists banned_voter_keys_voter_key_idx
  on public.banned_voter_keys (voter_key);

create or replace function public.is_voter_key_banned(p_voter_key text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.banned_voter_keys b
    where b.voter_key = nullif(trim(p_voter_key), '')
  );
$$;

grant execute on function public.is_voter_key_banned(text) to anon, authenticated;

alter table public.board_posts
  add column if not exists voter_key text;

alter table public.board_comments
  add column if not exists voter_key text;

create index if not exists board_posts_voter_key_idx
  on public.board_posts (voter_key)
  where voter_key is not null;

create index if not exists board_comments_voter_key_idx
  on public.board_comments (voter_key)
  where voter_key is not null;

create index if not exists partner_reviews_voter_key_idx
  on public.partner_reviews (voter_key);

-- Activity log for admin device management
create table if not exists public.voter_key_activity_log (
  id bigint generated by default as identity primary key,
  voter_key text not null,
  activity_type text not null check (activity_type in ('post', 'comment', 'review')),
  source_id uuid not null,
  board_type text,
  post_id uuid,
  post_title text,
  partner_id uuid,
  partner_name text,
  author_name text not null,
  title text,
  content_preview text not null default '',
  status integer,
  is_hidden boolean not null default false,
  source_deleted boolean not null default false,
  admin_dismissed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (activity_type, source_id)
);

create index if not exists voter_key_activity_log_key_idx
  on public.voter_key_activity_log (voter_key, created_at desc);

create index if not exists voter_key_activity_log_active_idx
  on public.voter_key_activity_log (admin_dismissed, created_at desc);

alter table public.voter_key_activity_log enable row level security;

create or replace function public.mark_voter_key_activity_source_deleted(
  p_activity_type text,
  p_source_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.voter_key_activity_log
  set source_deleted = true
  where activity_type = p_activity_type
    and source_id = p_source_id
    and not admin_dismissed;
end;
$$;

create or replace function public.trg_voter_key_activity_log_post()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.voter_key is null or char_length(trim(new.voter_key)) < 8 or coalesce(new.is_admin_managed, false) then
    return new;
  end if;

  insert into public.voter_key_activity_log (
    voter_key,
    activity_type,
    source_id,
    board_type,
    title,
    author_name,
    content_preview,
    status,
    is_hidden,
    created_at
  )
  values (
    trim(new.voter_key),
    'post',
    new.id,
    new.board_type,
    new.title,
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.status, 1),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_voter_key_activity_log_comment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post_title text;
begin
  if new.voter_key is null or char_length(trim(new.voter_key)) < 8 or coalesce(new.is_admin_managed, false) then
    return new;
  end if;

  select p.title into v_post_title from public.board_posts p where p.id = new.post_id;

  insert into public.voter_key_activity_log (
    voter_key,
    activity_type,
    source_id,
    post_id,
    post_title,
    author_name,
    content_preview,
    is_hidden,
    created_at
  )
  values (
    trim(new.voter_key),
    'comment',
    new.id,
    new.post_id,
    coalesce(v_post_title, '게시글'),
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_voter_key_activity_log_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_partner_name text;
begin
  if new.voter_key is null or char_length(trim(new.voter_key)) < 8 then
    return new;
  end if;

  select p.name into v_partner_name from public.partners p where p.id = new.partner_id;

  insert into public.voter_key_activity_log (
    voter_key,
    activity_type,
    source_id,
    partner_id,
    partner_name,
    author_name,
    content_preview,
    is_hidden,
    created_at
  )
  values (
    trim(new.voter_key),
    'review',
    new.id,
    new.partner_id,
    coalesce(v_partner_name, '업체'),
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_voter_key_activity_mark_deleted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'board_posts' then
    perform public.mark_voter_key_activity_source_deleted('post', old.id);
  elsif tg_table_name = 'board_comments' then
    perform public.mark_voter_key_activity_source_deleted('comment', old.id);
  elsif tg_table_name = 'partner_reviews' then
    perform public.mark_voter_key_activity_source_deleted('review', old.id);
  end if;
  return old;
end;
$$;

drop trigger if exists voter_key_activity_log_post_insert on public.board_posts;
create trigger voter_key_activity_log_post_insert
  after insert on public.board_posts
  for each row execute function public.trg_voter_key_activity_log_post();

drop trigger if exists voter_key_activity_log_comment_insert on public.board_comments;
create trigger voter_key_activity_log_comment_insert
  after insert on public.board_comments
  for each row execute function public.trg_voter_key_activity_log_comment();

drop trigger if exists voter_key_activity_log_review_insert on public.partner_reviews;
create trigger voter_key_activity_log_review_insert
  after insert on public.partner_reviews
  for each row execute function public.trg_voter_key_activity_log_review();

drop trigger if exists voter_key_activity_log_post_delete on public.board_posts;
create trigger voter_key_activity_log_post_delete
  before delete on public.board_posts
  for each row execute function public.trg_voter_key_activity_mark_deleted();

drop trigger if exists voter_key_activity_log_comment_delete on public.board_comments;
create trigger voter_key_activity_log_comment_delete
  before delete on public.board_comments
  for each row execute function public.trg_voter_key_activity_mark_deleted();

drop trigger if exists voter_key_activity_log_review_delete on public.partner_reviews;
create trigger voter_key_activity_log_review_delete
  before delete on public.partner_reviews
  for each row execute function public.trg_voter_key_activity_mark_deleted();

insert into public.voter_key_activity_log (
  voter_key, activity_type, source_id, partner_id, partner_name,
  author_name, content_preview, is_hidden, created_at
)
select
  trim(r.voter_key), 'review', r.id, r.partner_id, coalesce(p.name, '업체'),
  r.author_name, left(trim(coalesce(r.content, '')), 500),
  coalesce(r.is_hidden, false), r.created_at
from public.partner_reviews r
left join public.partners p on p.id = r.partner_id
where char_length(trim(r.voter_key)) >= 8
on conflict (activity_type, source_id) do nothing;

-- Guard RPCs (IP + device ban)
drop function if exists public.create_partner_review(uuid, text, text, text, text, inet);

create or replace function public.create_partner_review(
  p_partner_id uuid,
  p_author_name text,
  p_content text,
  p_password text,
  p_voter_key text,
  p_user_ip inet default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  new_count integer;
  store_admin_password boolean;
  ip_enabled boolean;
begin
  if char_length(trim(p_voter_key)) < 8 then
    raise exception 'Invalid voter key';
  end if;

  if public.is_voter_key_banned(p_voter_key) then
    raise exception 'Voter key banned';
  end if;

  if not exists (
    select 1 from partners where id = p_partner_id and is_active = true
  ) then
    raise exception 'Partner not found';
  end if;

  if char_length(trim(p_author_name)) = 0 or char_length(trim(p_content)) = 0 then
    raise exception 'Author and content are required';
  end if;

  if char_length(trim(p_password)) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  if p_user_ip is not null and public.is_ip_banned(p_user_ip) then
    raise exception 'IP banned';
  end if;

  ip_enabled := public.is_board_ip_moderation_enabled();
  store_admin_password := public.is_admin_partner_review_password_visible();

  insert into partner_reviews (
    partner_id, author_name, content, password_hash, voter_key,
    is_hidden, admin_visible_password, user_ip
  )
  values (
    p_partner_id, trim(p_author_name), trim(p_content),
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    trim(p_voter_key), false,
    case when store_admin_password then p_password else null end,
    case when ip_enabled then p_user_ip else null end
  )
  returning id into new_id;

  perform public.sync_partner_review_count(p_partner_id);
  select review_count into new_count from partners where id = p_partner_id;

  return jsonb_build_object('id', new_id, 'review_count', new_count);
end;
$$;

drop function if exists public.create_user_board_post(text, text, text, text, text, boolean, inet);
drop function if exists public.create_user_board_post(text, text, text, text, text, boolean, inet, text);

create or replace function public.create_user_board_post(
  p_board_type text,
  p_title text,
  p_author_name text,
  p_content text,
  p_password text,
  p_is_secret boolean default false,
  p_user_ip inet default null,
  p_voter_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  store_admin_password boolean;
  secret_enabled boolean;
  ip_enabled boolean;
  next_status integer;
  hide_post boolean;
  normalized_voter_key text;
begin
  normalized_voter_key := nullif(trim(p_voter_key), '');

  if normalized_voter_key is not null and char_length(normalized_voter_key) >= 8
     and public.is_voter_key_banned(normalized_voter_key) then
    raise exception 'Voter key banned';
  end if;

  if not public.is_user_writable_board(p_board_type) then
    raise exception 'Invalid board type';
  end if;

  if char_length(trim(p_password)) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  secret_enabled := public.is_board_secret_posts_enabled();
  if coalesce(p_is_secret, false) and not secret_enabled then
    raise exception 'Secret posts are disabled';
  end if;

  if p_user_ip is not null and public.is_ip_banned(p_user_ip) then
    raise exception 'IP banned';
  end if;

  ip_enabled := public.is_board_ip_moderation_enabled();

  if ip_enabled then
    if p_user_ip is null then
      raise exception 'Client IP is required';
    end if;
    next_status := public.resolve_board_post_status_for_ip(p_user_ip);
  else
    next_status := 1;
  end if;

  hide_post := next_status >= 3;
  store_admin_password := public.is_admin_user_password_visible();

  insert into board_posts (
    board_type, title, author_name, content, password_hash,
    admin_visible_password, is_secret, user_ip, voter_key, status, is_hidden
  )
  values (
    p_board_type, trim(p_title), trim(p_author_name), p_content,
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    case when store_admin_password then p_password else null end,
    case when secret_enabled then coalesce(p_is_secret, false) else false end,
    case when ip_enabled then p_user_ip else null end,
    case when normalized_voter_key is not null and char_length(normalized_voter_key) >= 8
      then normalized_voter_key else null end,
    next_status, hide_post
  )
  returning id into new_id;

  return new_id;
end;
$$;

drop function if exists public.create_user_board_comment(uuid, text, text, text, uuid, boolean, inet);
drop function if exists public.create_user_board_comment(uuid, text, text, text, uuid, boolean, inet, text);

create or replace function public.create_user_board_comment(
  p_post_id uuid,
  p_author_name text,
  p_content text,
  p_password text,
  p_parent_id uuid default null,
  p_is_secret boolean default false,
  p_user_ip inet default null,
  p_voter_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  new_id uuid;
  post_hidden boolean;
  parent_post_id uuid;
  parent_hidden boolean;
  store_admin_password boolean;
  secret_enabled boolean;
  ip_enabled boolean;
  normalized_voter_key text;
begin
  normalized_voter_key := nullif(trim(p_voter_key), '');

  if normalized_voter_key is not null and char_length(normalized_voter_key) >= 8
     and public.is_voter_key_banned(normalized_voter_key) then
    raise exception 'Voter key banned';
  end if;

  select is_hidden into post_hidden from board_posts where id = p_post_id;
  if post_hidden is null or post_hidden then
    raise exception 'Post not found';
  end if;

  if p_parent_id is not null then
    select post_id, is_hidden into parent_post_id, parent_hidden
    from board_comments where id = p_parent_id;
    if parent_post_id is null or parent_hidden or parent_post_id <> p_post_id then
      raise exception 'Parent comment not found';
    end if;
  end if;

  if char_length(trim(p_author_name)) = 0 or char_length(trim(p_content)) = 0 then
    raise exception 'Author and content are required';
  end if;

  if char_length(trim(p_password)) < 4 then
    raise exception 'Password must be at least 4 characters';
  end if;

  secret_enabled := public.is_board_secret_comments_enabled();
  if coalesce(p_is_secret, false) and not secret_enabled then
    raise exception 'Secret comments are disabled';
  end if;

  if p_user_ip is not null and public.is_ip_banned(p_user_ip) then
    raise exception 'IP banned';
  end if;

  ip_enabled := public.is_board_ip_moderation_enabled();
  store_admin_password := public.is_admin_user_password_visible();

  insert into board_comments (
    post_id, parent_id, author_name, content, password_hash,
    admin_visible_password, is_secret, user_ip, voter_key
  )
  values (
    p_post_id, p_parent_id, trim(p_author_name), trim(p_content),
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    case when store_admin_password then p_password else null end,
    case when secret_enabled then coalesce(p_is_secret, false) else false end,
    case when ip_enabled then p_user_ip else null end,
    case when normalized_voter_key is not null and char_length(normalized_voter_key) >= 8
      then normalized_voter_key else null end
  )
  returning id into new_id;

  return new_id;
end;
$$;

drop function if exists public.admin_list_voter_key_activity_summary();

create function public.admin_list_voter_key_activity_summary()
returns table (
  voter_key text,
  post_count bigint,
  comment_count bigint,
  review_count bigint,
  max_status integer,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    l.voter_key,
    count(*) filter (where l.activity_type = 'post') as post_count,
    count(*) filter (where l.activity_type = 'comment') as comment_count,
    count(*) filter (where l.activity_type = 'review') as review_count,
    coalesce(max(l.status) filter (where l.activity_type = 'post'), 1) as max_status,
    max(l.created_at) as last_seen_at
  from public.voter_key_activity_log l
  where not l.admin_dismissed
  group by l.voter_key
  order by max(l.created_at) desc;
$$;

drop function if exists public.admin_list_voter_key_activity_for_key(text);

create function public.admin_list_voter_key_activity_for_key(p_voter_key text)
returns table (
  id bigint,
  activity_type text,
  source_id uuid,
  board_type text,
  post_id uuid,
  post_title text,
  partner_id uuid,
  partner_name text,
  author_name text,
  title text,
  content_preview text,
  status integer,
  is_hidden boolean,
  source_deleted boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    l.id, l.activity_type, l.source_id, l.board_type, l.post_id, l.post_title,
    l.partner_id, l.partner_name, l.author_name, l.title, l.content_preview,
    l.status, l.is_hidden, l.source_deleted, l.created_at
  from public.voter_key_activity_log l
  where not l.admin_dismissed
    and l.voter_key = nullif(trim(p_voter_key), '')
  order by l.created_at desc
  limit 100;
$$;

drop function if exists public.admin_dismiss_voter_key_activity_log(bigint);

create or replace function public.admin_dismiss_voter_key_activity_log(p_log_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.voter_key_activity_log
  set admin_dismissed = true
  where id = p_log_id and not admin_dismissed;
  return found;
end;
$$;

grant execute on function public.create_partner_review(uuid, text, text, text, text, inet) to anon, authenticated;
grant execute on function public.create_user_board_post(text, text, text, text, text, boolean, inet, text) to anon, authenticated;
grant execute on function public.create_user_board_comment(uuid, text, text, text, uuid, boolean, inet, text) to anon, authenticated;
grant execute on function public.admin_list_voter_key_activity_summary() to authenticated;
grant execute on function public.admin_list_voter_key_activity_for_key(text) to authenticated;
grant execute on function public.admin_dismiss_voter_key_activity_log(bigint) to authenticated;

drop function if exists public.admin_list_partner_reviews(uuid);

create function public.admin_list_partner_reviews(p_partner_id uuid default null)
returns table (
  id uuid,
  partner_id uuid,
  partner_name text,
  author_name text,
  content text,
  is_hidden boolean,
  admin_visible_password text,
  user_ip inet,
  voter_key text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    r.id,
    r.partner_id,
    p.name as partner_name,
    r.author_name,
    r.content,
    r.is_hidden,
    r.admin_visible_password,
    r.user_ip,
    r.voter_key,
    r.created_at
  from partner_reviews r
  join partners p on p.id = r.partner_id
  where p_partner_id is null or r.partner_id = p_partner_id
  order by r.created_at desc;
$$;

grant execute on function public.admin_list_partner_reviews(uuid) to authenticated;

notify pgrst, 'reload schema';
