-- IP 활동 로그: 사용자 삭제 후에도 관리자 IP 목록에 남기고, 관리자가 목록에서 숨길 수 있음

create table if not exists public.ip_activity_log (
  id bigint generated by default as identity primary key,
  user_ip inet not null,
  activity_type text not null check (activity_type in ('post', 'comment', 'review')),
  source_id uuid not null,
  board_type text,
  post_id uuid,
  post_title text,
  partner_id uuid,
  partner_name text,
  author_name text not null,
  title text,
  content_preview text not null default '',
  status integer,
  is_hidden boolean not null default false,
  source_deleted boolean not null default false,
  admin_dismissed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (activity_type, source_id)
);

create index if not exists ip_activity_log_user_ip_idx
  on public.ip_activity_log (user_ip, created_at desc);

create index if not exists ip_activity_log_active_idx
  on public.ip_activity_log (admin_dismissed, created_at desc);

alter table public.ip_activity_log enable row level security;

create or replace function public.mark_ip_activity_source_deleted(
  p_activity_type text,
  p_source_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ip_activity_log
  set source_deleted = true
  where activity_type = p_activity_type
    and source_id = p_source_id
    and not admin_dismissed;
end;
$$;

create or replace function public.trg_ip_activity_log_post()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.user_ip is null or coalesce(new.is_admin_managed, false) then
    return new;
  end if;

  insert into public.ip_activity_log (
    user_ip,
    activity_type,
    source_id,
    board_type,
    title,
    author_name,
    content_preview,
    status,
    is_hidden,
    created_at
  )
  values (
    new.user_ip,
    'post',
    new.id,
    new.board_type,
    new.title,
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.status, 1),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_ip_activity_log_comment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post_title text;
begin
  if new.user_ip is null or coalesce(new.is_admin_managed, false) then
    return new;
  end if;

  select p.title
  into v_post_title
  from public.board_posts p
  where p.id = new.post_id;

  insert into public.ip_activity_log (
    user_ip,
    activity_type,
    source_id,
    post_id,
    post_title,
    author_name,
    content_preview,
    is_hidden,
    created_at
  )
  values (
    new.user_ip,
    'comment',
    new.id,
    new.post_id,
    coalesce(v_post_title, '게시글'),
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_ip_activity_log_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_partner_name text;
begin
  if new.user_ip is null then
    return new;
  end if;

  select p.name
  into v_partner_name
  from public.partners p
  where p.id = new.partner_id;

  insert into public.ip_activity_log (
    user_ip,
    activity_type,
    source_id,
    partner_id,
    partner_name,
    author_name,
    content_preview,
    is_hidden,
    created_at
  )
  values (
    new.user_ip,
    'review',
    new.id,
    new.partner_id,
    coalesce(v_partner_name, '업체'),
    new.author_name,
    left(trim(coalesce(new.content, '')), 500),
    coalesce(new.is_hidden, false),
    new.created_at
  )
  on conflict (activity_type, source_id) do nothing;

  return new;
end;
$$;

create or replace function public.trg_ip_activity_mark_deleted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'board_posts' then
    perform public.mark_ip_activity_source_deleted('post', old.id);
  elsif tg_table_name = 'board_comments' then
    perform public.mark_ip_activity_source_deleted('comment', old.id);
  elsif tg_table_name = 'partner_reviews' then
    perform public.mark_ip_activity_source_deleted('review', old.id);
  end if;

  return old;
end;
$$;

drop trigger if exists ip_activity_log_post_insert on public.board_posts;
create trigger ip_activity_log_post_insert
  after insert on public.board_posts
  for each row
  execute function public.trg_ip_activity_log_post();

drop trigger if exists ip_activity_log_comment_insert on public.board_comments;
create trigger ip_activity_log_comment_insert
  after insert on public.board_comments
  for each row
  execute function public.trg_ip_activity_log_comment();

drop trigger if exists ip_activity_log_review_insert on public.partner_reviews;
create trigger ip_activity_log_review_insert
  after insert on public.partner_reviews
  for each row
  execute function public.trg_ip_activity_log_review();

drop trigger if exists ip_activity_log_post_delete on public.board_posts;
create trigger ip_activity_log_post_delete
  before delete on public.board_posts
  for each row
  execute function public.trg_ip_activity_mark_deleted();

drop trigger if exists ip_activity_log_comment_delete on public.board_comments;
create trigger ip_activity_log_comment_delete
  before delete on public.board_comments
  for each row
  execute function public.trg_ip_activity_mark_deleted();

drop trigger if exists ip_activity_log_review_delete on public.partner_reviews;
create trigger ip_activity_log_review_delete
  before delete on public.partner_reviews
  for each row
  execute function public.trg_ip_activity_mark_deleted();

insert into public.ip_activity_log (
  user_ip,
  activity_type,
  source_id,
  board_type,
  title,
  author_name,
  content_preview,
  status,
  is_hidden,
  created_at
)
select
  p.user_ip,
  'post',
  p.id,
  p.board_type,
  p.title,
  p.author_name,
  left(trim(coalesce(p.content, '')), 500),
  coalesce(p.status, 1),
  coalesce(p.is_hidden, false),
  p.created_at
from public.board_posts p
where p.user_ip is not null
  and coalesce(p.is_admin_managed, false) = false
on conflict (activity_type, source_id) do nothing;

insert into public.ip_activity_log (
  user_ip,
  activity_type,
  source_id,
  post_id,
  post_title,
  author_name,
  content_preview,
  is_hidden,
  created_at
)
select
  c.user_ip,
  'comment',
  c.id,
  c.post_id,
  coalesce(p.title, '게시글'),
  c.author_name,
  left(trim(coalesce(c.content, '')), 500),
  coalesce(c.is_hidden, false),
  c.created_at
from public.board_comments c
left join public.board_posts p on p.id = c.post_id
where c.user_ip is not null
  and coalesce(c.is_admin_managed, false) = false
on conflict (activity_type, source_id) do nothing;

insert into public.ip_activity_log (
  user_ip,
  activity_type,
  source_id,
  partner_id,
  partner_name,
  author_name,
  content_preview,
  is_hidden,
  created_at
)
select
  r.user_ip,
  'review',
  r.id,
  r.partner_id,
  coalesce(p.name, '업체'),
  r.author_name,
  left(trim(coalesce(r.content, '')), 500),
  coalesce(r.is_hidden, false),
  r.created_at
from public.partner_reviews r
left join public.partners p on p.id = r.partner_id
where r.user_ip is not null
on conflict (activity_type, source_id) do nothing;

drop function if exists public.admin_list_ip_activity_summary();

create function public.admin_list_ip_activity_summary()
returns table (
  ip text,
  post_count bigint,
  comment_count bigint,
  review_count bigint,
  max_status integer,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    host(l.user_ip) as ip,
    count(*) filter (where l.activity_type = 'post') as post_count,
    count(*) filter (where l.activity_type = 'comment') as comment_count,
    count(*) filter (where l.activity_type = 'review') as review_count,
    coalesce(max(l.status) filter (where l.activity_type = 'post'), 1) as max_status,
    max(l.created_at) as last_seen_at
  from public.ip_activity_log l
  where not l.admin_dismissed
  group by l.user_ip
  order by max(l.created_at) desc;
$$;

drop function if exists public.admin_list_ip_activity_for_ip(text);

create function public.admin_list_ip_activity_for_ip(p_ip text)
returns table (
  id bigint,
  activity_type text,
  source_id uuid,
  board_type text,
  post_id uuid,
  post_title text,
  partner_id uuid,
  partner_name text,
  author_name text,
  title text,
  content_preview text,
  status integer,
  is_hidden boolean,
  source_deleted boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select
    l.id,
    l.activity_type,
    l.source_id,
    l.board_type,
    l.post_id,
    l.post_title,
    l.partner_id,
    l.partner_name,
    l.author_name,
    l.title,
    l.content_preview,
    l.status,
    l.is_hidden,
    l.source_deleted,
    l.created_at
  from public.ip_activity_log l
  where not l.admin_dismissed
    and l.user_ip = p_ip::inet
  order by l.created_at desc
  limit 100;
$$;

drop function if exists public.admin_dismiss_ip_activity_log(bigint);

create or replace function public.admin_dismiss_ip_activity_log(p_log_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ip_activity_log
  set admin_dismissed = true
  where id = p_log_id
    and not admin_dismissed;

  return found;
end;
$$;

grant execute on function public.admin_list_ip_activity_summary() to authenticated;
grant execute on function public.admin_list_ip_activity_for_ip(text) to authenticated;
grant execute on function public.admin_dismiss_ip_activity_log(bigint) to authenticated;

notify pgrst, 'reload schema';
